---
title: "ProfiencyTest2"
format: pdf
editor: visual
---
## Task 1
```{r}
for (i in 1:3) {
  print(mtcars$mpg[i])
}
```
## Task 2 
```{r}
count_above <- function(vector, cutoff) { # see explanation L24
  count <- 0 # creates a "count" for the scenario below

  for (i in 1:length(vector)) { # takes that for every vector,
    if (vector > cutoff) { # if a vector is greater than cutoff
      count <- count + 1 # than add to the count
      }
  }
  return(count) # resets the count to 0
}
# creates a function named count_above containing the variables
# vector and cutoff.
```
```{r}
for (i in 1:nrow(iris)) {
  if (iris$Sepal.Length[i] > 6) {
    print(iris$Septal.Length)
  }
}
# The code printed no Sepal Lengths, so there are no iris flowers
# in the dataset with sepal lengths greater than 6 cm. 

for (i in 1:nrow(mtcars)) {
  if (mtcars$disp[i] >= 150) {
    print(mtcars$disp)
  }
}
# The code printed 4 rows of cars that had a disp greater than
# or equal to 150. 
```
## Task 3
Masking functions involves using functions such as eval: FALSE or echo: FALSE to mask other functions' output to make the rendered document "clean" and more readable. 

## Task 4
```{r}
iris$Sepal.Length[1] # The code returns the sepal length value of # the first row in the data set
iris[1,1]
```

